language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_7582392b6f43_key -iv $encrypted_7582392b6f43_iv -in application.properties.enc -out src/main/resources/application.properties -d