language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_c6e3754f99a8_key -iv $encrypted_c6e3754f99a8_iv -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d